### ISSUE TITLE
LMTP-Server is not reachable

### ISSUE THREAD

**Issue by BlackScreen** [christianbur/docker_projects#3]
Hey there,
I was using getmail without problems for a longer time. Now it does not work. I have an idea why, but no clue how to solve it.

First to my structure:
My mailcow is located at "/opt/containers/mailcow".
"getmail" is located at "/opt/containers/getmail".

My mailcow-override-file looks like this:

```
version: '2.1'

services:
    dovecot-mailcow:
      networks:
        - getmail

networks:
  getmail:
    external: true
```

And my getmail-compose-file looks like this:

```
version: '2.4'

services:
    getmail:
      image: cb/getmail
      container_name: getmail
      build: ./Dockerfiles
      volumes:
        - ./conf/settings.ini:/app/settings.ini:ro
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
      restart: always
      mem_limit: 100m
      mem_reservation: 20m
      labels:
        - "com.centurylinklabs.watchtower.enable=false"
      networks:
        getmail:

networks:
    getmail:
      external: false
      name: getmail
      driver: bridge
      driver_opts:
        com.docker.network.bridge.name: br-getmail
```

The error message in the logs looks like this - for every thread:

```
2021-02-16 09:23:47,975 - Thread-XYZ - ERROR: LMTP deliver (LMTP-Server is not reachable): [Errno -3] Try again
2021-02-16 09:23:47,976 - Thread-XYZ - INFO: LMTP deliver: start -- LMTP host: dovecot-mailcow:24
```

Normally I start getmail before mailcow. getmail creates the network and then I start mailcow.
But, dovecot does not join the getmail-network. This is my theory why it is not working - I do not know if this is correct.
I then added the dovecot container manually (via Portainer) to the getmail network, but the error persists.

I have no clue why suddenly it does not work.
mailcow and getmail are and the latest versions.

Can you help me with my problem?
It would be greatly appreciated. :)

**Comment by christianbur** [comment]
Is dovecot-mailcow in the getmail network? 

https://github.com/christianbur/docker_projects/blob/master/getmail/mailcow-dockerized_docker-compose.override.yml

**Comment by BlackScreen** [comment]
> Is dovecot-mailcow in the getmail network?
> 
> The getmail network should be external, otherwise there are problems, if getmail is not started mailcow-dovecot is.

Theoretically yes (see my override file), practically no (Portainer shows only getmail in the getmail network).
How to create the getmail network? I could try that solutin.

**Comment by christianbur** [comment]
The getmail netwerk should be external in both files, see my two examples (links above)

**Comment by BlackScreen** [comment]
> The getmail netwerk should be external in both files, see my two examples (links above)

Thanks, I saw them and this line:

`docker network create --driver=bridge --ipv6 --subnet=fdcb:9c90:23:11::/64 --gateway=fdcb:9c90:23:11::1 --subnet=172.23.11.0/24 --gateway=172.23.11.1 -o "com.docker.network.bridge.name"="br-getmail" network-getmail`

I just do not know which subnets to use. Are the ones in your example the exact subnets of the mailcow network or different ones?

**Comment by BlackScreen** [comment]
I can create a network with this line.
`docker network create --driver=bridge -o "com.docker.network.bridge.name"="br-getmail" getmail`
But then the mailcow container does not get added to the network when starting mailcow.

This line:
`docker network create --driver=bridge --ipv6 -o "com.docker.network.bridge.name"="br-getmail" getmail`
Gives me this error:
`Error response from daemon: could not find an available, non-overlapping IPv6 address pool among the defaults to assign to the network`

I am running blind here, sorry for bugging you. :(

**Comment by christianbur** [comment]
Why don't you just use the command from my example?
The subnets in the example are just freely chosen (172.16/12, rfc1918 and unique local address (ULA)), they must not be used on your server otherwise.

In the two docker-compose files, the network must then be defined as external (see example).
If you don't do this there will be problems when you restart the getmail projet and mailcow is still running.

docker network rm getmail

docker network create --driver=bridge --ipv6 --subnet=fdcb:9c90:23:11::/64 --gateway=fdcb:9c90:23:11::1 --subnet=172.23.11.0/24 --gateway=172.23.11.1 -o "com.docker.network.bridge.name"="br-getmail" getmail

**Comment by BlackScreen** [comment]
> Why don't you just use the command from my example?

I did before, it errors out with...
`Error response from daemon: Pool overlaps with other one on this address space`

In Portainer these are the networks I have...
![image](https://user-images.githubusercontent.com/17316492/108085377-8df41400-7075-11eb-9e96-b6c508ef97e8.png)

**Comment by christianbur** [comment]
Wow, with the /16 range you can run a whole data center :-) 

Then just use another free range.


docker network create --driver=bridge --ipv6 --subnet=fdcb:9c90:24:11::/64 --gateway=fdcb:9c90:24:11::1 --subnet=172.24.11.0/24 --gateway=172.24.11.1 -o "com.docker.network.bridge.name"="br-getmail" getmail

**Comment by BlackScreen** [comment]
> Wow, with the /16 range you can run a whole data center :-)

Well, those were the defaults of the containers I use. :D

We are one step further:

> docker network create --driver=bridge --ipv6 --subnet=fdcb:9c90:24:11::/64 --gateway=fdcb:9c90:24:11::1 --subnet=172.24.11.0/24 --gateway=172.24.11.1 -o "com.docker.network.bridge.name"="br-getmail" getmail

This worked. I could create the network. :)

BUT:
I do get the the same warning when starting mailcow as before...

`WARNING: Some networks were defined but are not used by any service: getmail`

And the dovecot-container does not use the getmail network.

Even further, getmail now spams the log files with this...

```
2021-02-16 17:03:37,642 - Thread-XYZ - INFO: LMTP deliver: start -- LMTP host: dovecot-mailcow:24
2021-02-16 17:03:37,647 - Thread-XYZ - ERROR: LMTP deliver (LMTP-Server is not reachable): [Errno -2] Name does not resolve
```

One step further, two steps back, I guess? :D
Thank you so much for your help. Let me know if I can support you anyway! :)

**Comment by christianbur** [comment]
The file must be named docker-compose.override.yml


https://github.com/christianbur/docker_projects/blob/master/getmail/mailcow-dockerized_docker-compose.override.yml

your file:

version: '2.1'
services:

    dovecot-mailcow:
      networks:
        getmail:

networks:
  getmail:
    external: true

**Comment by BlackScreen** [comment]
Ok, this is embarassing. It was my own fault. :(

Short explanation:
In the mailcow-override-file (which was correctly named) I had labels for watchtower to not automatically update mailcow - for every container. So, there were to override entries for dovecot-mailcow.
I then changed it to this:

```
    dovecot-mailcow:
      labels:
        - "com.centurylinklabs.watchtower.enable=false"
      networks:
        getmail:
```

And it works now! :)

So, I fixed the network - thanks to your help, and I found my own stupid mistake.

Again: Thank you so much for your help and your tool. If I can support you a little, let me know! :)
